export const FETCH_DISHES_REQUEST = 'FETCH_DISHES_REQUEST';
export const FETCH_DISHES_SUCCESS = 'FETCH_DISHES_SUCCESS';
export const FETCH_DISHES_FAILURE = 'FETCH_DISHES_FAILURE';
export const FETCH_DISHES_FINALLY = 'FETCH_DISHES_FINALLY';
export const ADD_NEW_DISH = 'ADD_NEW_DISH';
export const DELETE_DISH = 'DELETE_DISH';
export const EDIT_DISH = 'EDIT_DISH';
export const EDIT_EACH_LINE = 'EDIT_EACH_LINE';
